# EconomicBridge — Secrets Manager entries per CLAUDE.md §8.
#
# These resources create EMPTY secrets. The actual values are populated
# out-of-band via:
#
#   aws secretsmanager put-secret-value \
#     --secret-id /economicbridge/staging/nasa_firms/api_key \
#     --secret-string '<the real key>' \
#     --profile economicbridge
#
# Why empty: keys must never appear in tfvars / state. Terraform manages
# the *existence* and *access policies*; the rotation of the value is
# operator-controlled (per CLAUDE.md §4.1).
#
# RDS DB password is generated by Terraform (random_password resource in
# rds.tf) and written to a separate secret — it's not in this list because
# Terraform owns its lifecycle end-to-end.

# ─── Database password (generated, owned end-to-end by Terraform) ──────

resource "random_password" "rds" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?" # safe set; no quotes / slashes
}

resource "aws_secretsmanager_secret" "rds_password" {
  name                    = "/${var.project_name}/${var.environment}/rds/master_password"
  description             = "RDS PostgreSQL master password — generated by Terraform"
  recovery_window_in_days = 7
  kms_key_id              = "alias/aws/secretsmanager" # AWS-managed CMK

  tags = {
    Name = "${local.name_prefix}-rds-password"
  }
}

resource "aws_secretsmanager_secret_version" "rds_password" {
  secret_id     = aws_secretsmanager_secret.rds_password.id
  secret_string = random_password.rds.result
}

# ─── JWT signing key (generated, owned end-to-end by Terraform) ────────
#
# The API signs access/refresh/invite tokens with this (CLAUDE.md §4.1). Like
# the RDS password it's a random secret Terraform owns — never a tfvars value.
# Injected into the api task as JWT_SECRET_KEY via the secrets block in ecs.tf.
# Rotating it (taint + apply) invalidates all live sessions, which is the point.

resource "random_password" "jwt" {
  length  = 64
  special = false # base62 — safe in a JWT HS256 key, no escaping concerns
}

resource "aws_secretsmanager_secret" "jwt" {
  name                    = "/${var.project_name}/${var.environment}/auth/jwt_secret_key"
  description             = "JWT signing key — generated by Terraform"
  recovery_window_in_days = 7
  kms_key_id              = "alias/aws/secretsmanager"

  tags = {
    Name = "${local.name_prefix}-jwt-secret"
  }
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id     = aws_secretsmanager_secret.jwt.id
  secret_string = random_password.jwt.result
}

# ─── External-provider secrets (created empty, populated by operator) ──

resource "aws_secretsmanager_secret" "external" {
  for_each = toset(local.secret_paths)

  name                    = "/${var.project_name}/${var.environment}/${each.value}"
  description             = "External provider credential — populate via `aws secretsmanager put-secret-value`"
  recovery_window_in_days = 7
  kms_key_id              = "alias/aws/secretsmanager"

  tags = {
    Name     = "${local.name_prefix}-secret-${replace(each.value, "/", "-")}"
    Provider = split("/", each.value)[0]
  }
}

# Placeholder value so the secret has *something* — prevents tasks from
# crashing on first deploy. Operator overrides with the real value later.
# `lifecycle.ignore_changes` ensures Terraform doesn't fight the operator.
resource "aws_secretsmanager_secret_version" "external_placeholder" {
  for_each = aws_secretsmanager_secret.external

  secret_id     = each.value.id
  secret_string = "PLACEHOLDER_NOT_SET"

  lifecycle {
    ignore_changes = [secret_string, version_stages]
  }
}
