#!/usr/bin/env python3
"""
Tenant Generator — EconomicBridge
==================================
Reads tenants.yaml and provisions a PostgreSQL schema for the specified tenant.
Creates the schema with all required base tables.

Usage:
    python scripts/generate_tenant.py --tenant-id kebbi
    make tenant-provision TENANT=kebbi
"""

import argparse
import sys
from pathlib import Path

import yaml


TENANTS_FILE = Path(__file__).parent.parent / "tenants.yaml"


def load_tenants() -> dict:
    """Load and parse the tenants.yaml configuration file."""
    if not TENANTS_FILE.exists():
        print(f"✗ tenants.yaml not found at {TENANTS_FILE}")
        sys.exit(1)
    with open(TENANTS_FILE) as f:
        return yaml.safe_load(f)


def get_tenant(tenant_id: str) -> dict | None:
    """Find a tenant by ID from the configuration."""
    config = load_tenants()
    for tenant in config.get("tenants", []):
        if tenant.get("id") == tenant_id:
            return tenant
    return None


def generate_schema_sql(tenant: dict) -> str:
    """Generate the SQL to create a tenant schema with all base tables.

    Args:
        tenant: Tenant configuration dictionary from tenants.yaml.

    Returns:
        SQL string to execute for schema creation.
    """
    schema_name = f"tenant_{tenant['id']}"

    return f"""
-- =============================================
-- Schema for tenant: {tenant['name']}
-- ID: {tenant['id']}
-- Type: {tenant['type']}
-- Generated by: scripts/generate_tenant.py
-- =============================================

CREATE SCHEMA IF NOT EXISTS {schema_name};

-- Users table
CREATE TABLE IF NOT EXISTS {schema_name}.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'viewer',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    last_login_at TIMESTAMPTZ,
    UNIQUE(email, tenant_id)
);

-- Audit log table (INSERT-only — application user has no DELETE/UPDATE)
CREATE TABLE IF NOT EXISTS {schema_name}.audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    user_id UUID,
    action VARCHAR(50) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id UUID,
    old_value JSONB,
    new_value JSONB,
    trace_id UUID NOT NULL DEFAULT uuid_generate_v4(),
    ip_address INET,
    user_agent TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Alert events table
CREATE TABLE IF NOT EXISTS {schema_name}.alert_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    alert_type VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    title VARCHAR(500) NOT NULL,
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    geometry GEOMETRY(Point, 4326),
    confidence DOUBLE PRECISION,
    model_version VARCHAR(50),
    is_acknowledged BOOLEAN NOT NULL DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID NOT NULL
);

-- Tenant configuration record
CREATE TABLE IF NOT EXISTS {schema_name}.tenant_configs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    config_key VARCHAR(255) NOT NULL,
    config_value JSONB NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID NOT NULL,
    UNIQUE(tenant_id, config_key)
);

-- DPA processing records (NDPA 2023 compliance)
CREATE TABLE IF NOT EXISTS {schema_name}.dpa_processing_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL,
    processing_purpose TEXT NOT NULL,
    lawful_basis VARCHAR(100) NOT NULL,
    data_categories TEXT[] NOT NULL,
    retention_period_days INTEGER NOT NULL DEFAULT 365,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_{schema_name}_users_email
    ON {schema_name}.users(email);
CREATE INDEX IF NOT EXISTS idx_{schema_name}_audit_log_timestamp
    ON {schema_name}.audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_{schema_name}_audit_log_user
    ON {schema_name}.audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_{schema_name}_alerts_type
    ON {schema_name}.alert_events(alert_type);
CREATE INDEX IF NOT EXISTS idx_{schema_name}_alerts_created
    ON {schema_name}.alert_events(created_at);

-- Grant permissions to application user
GRANT USAGE ON SCHEMA {schema_name} TO economicbridge_app;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {schema_name} TO economicbridge_app;

-- Audit log: INSERT only (no UPDATE, no DELETE)
REVOKE UPDATE, DELETE ON {schema_name}.audit_log FROM economicbridge_app;
GRANT INSERT, SELECT ON {schema_name}.audit_log TO economicbridge_app;

-- Auto-update trigger for updated_at columns
CREATE OR REPLACE FUNCTION {schema_name}.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    -- users table trigger
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_{schema_name}_users_updated_at'
    ) THEN
        CREATE TRIGGER trg_{schema_name}_users_updated_at
            BEFORE UPDATE ON {schema_name}.users
            FOR EACH ROW EXECUTE FUNCTION {schema_name}.update_updated_at();
    END IF;

    -- alert_events table trigger
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_{schema_name}_alerts_updated_at'
    ) THEN
        CREATE TRIGGER trg_{schema_name}_alerts_updated_at
            BEFORE UPDATE ON {schema_name}.alert_events
            FOR EACH ROW EXECUTE FUNCTION {schema_name}.update_updated_at();
    END IF;
END
$$;
"""


def main() -> None:
    """Entry point for tenant generation script."""
    parser = argparse.ArgumentParser(
        description="Generate PostgreSQL schema for an EconomicBridge tenant"
    )
    parser.add_argument(
        "--tenant-id",
        required=True,
        help="Tenant ID from tenants.yaml (e.g., kebbi)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Write SQL to file instead of stdout (default: stdout)",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute SQL directly against the database (requires DATABASE_URL env var)",
    )
    args = parser.parse_args()

    tenant = get_tenant(args.tenant_id)
    if tenant is None:
        print(f"✗ Tenant '{args.tenant_id}' not found in tenants.yaml")
        sys.exit(1)

    sql = generate_schema_sql(tenant)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(sql)
        print(f"✓ Schema SQL written to {output_path}")
    elif args.execute:
        import os
        try:
            import psycopg2  # type: ignore[import-untyped]
        except ImportError:
            print("✗ psycopg2 not installed. Run: pip install psycopg2-binary")
            sys.exit(1)

        database_url = os.environ.get("DATABASE_URL", "")
        if not database_url:
            print("✗ DATABASE_URL environment variable not set")
            sys.exit(1)

        # Convert async URL to sync if needed
        database_url = database_url.replace("postgresql+asyncpg://", "postgresql://")

        conn = psycopg2.connect(database_url)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(sql)
        conn.close()
        print(f"✓ Schema for tenant '{args.tenant_id}' ({tenant['name']}) created successfully")
    else:
        print(sql)


if __name__ == "__main__":
    main()
