#!/usr/bin/env python3
"""
Prompt Version Control System — EconomicBridge
================================================
Tracks every AI prompt used to generate code in this project.
Run: python scripts/save_prompt.py --description "add conflict model"

Why this exists:
- Reproducibility: re-run a prompt that generated good output
- Audit trail: know what generated every piece of code
- Improvement: compare prompt v1 vs v2 output quality
"""

import json
import sys
import hashlib
from datetime import datetime, UTC
from pathlib import Path
import argparse


PROMPTS_DIR = Path(__file__).parent.parent / "prompts" / "versions"
INDEX_FILE = Path(__file__).parent.parent / "prompts" / "index.json"


def load_index() -> list[dict]:
    """Load the prompt index file."""
    if not INDEX_FILE.exists():
        return []
    with open(INDEX_FILE) as f:
        return json.load(f)


def save_index(index: list[dict]) -> None:
    """Save the prompt index file."""
    INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(INDEX_FILE, "w") as f:
        json.dump(index, f, indent=2, default=str)


def save_prompt(
    description: str,
    prompt_text: str | None = None,
    files_generated: list[str] | None = None,
    model: str = "claude-opus-4-5",
) -> dict:
    """
    Save a prompt to version history.

    Args:
        description: Short description of what this prompt generates.
        prompt_text: The actual prompt text (optional — can be added later).
        files_generated: List of files this prompt generated.
        model: The Claude model used.

    Returns:
        Prompt metadata dict.
    """
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    index = load_index()

    version_number = len(index) + 1
    version_id = f"{version_number:04d}"
    timestamp = datetime.now(UTC).isoformat()

    if prompt_text:
        content_hash = hashlib.sha256(prompt_text.encode()).hexdigest()[:12]
    else:
        content_hash = "manual"

    filename = f"prompt-{version_id}-{content_hash}.md"
    filepath = PROMPTS_DIR / filename

    metadata = {
        "version": version_id,
        "description": description,
        "timestamp": timestamp,
        "model": model,
        "files_generated": files_generated or [],
        "filename": filename,
        "content_hash": content_hash,
    }

    # Write the prompt file
    prompt_content = f"""# Prompt {version_id}: {description}

**Date:** {timestamp}
**Model:** {model}
**Files generated:** {', '.join(files_generated or []) or 'not specified'}

---

## Prompt Text

{prompt_text or '(Add prompt text here)'}

---

## Notes

(Add notes about what worked well or what to change next time)
"""

    with open(filepath, "w") as f:
        f.write(prompt_content)

    index.append(metadata)
    save_index(index)

    print(f"✓ Saved prompt version {version_id}: {description}")
    print(f"  File: {filepath}")
    return metadata


def list_prompts() -> None:
    """Print all saved prompts."""
    index = load_index()
    if not index:
        print("No prompts saved yet.")
        return

    print(f"\n{'ID':>6}  {'Date':>25}  {'Description'}")
    print("─" * 70)
    for entry in index:
        print(f"{entry['version']:>6}  {entry['timestamp'][:19]:>25}  {entry['description']}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Prompt Version Control")
    parser.add_argument(
        "--description", help="Save a new prompt with this description"
    )
    parser.add_argument(
        "--files", nargs="*", help="Files generated by this prompt"
    )
    parser.add_argument("--model", default="claude-opus-4-5")
    parser.add_argument(
        "--list", action="store_true", help="List all saved prompts"
    )

    args = parser.parse_args()

    if args.list:
        list_prompts()
    elif args.description:
        save_prompt(
            description=args.description,
            files_generated=args.files,
            model=args.model,
        )
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
