"""Render the published legal texts into the website.

    python docs/legal/build_legal_pages.py

The Markdown files beside this script are the source of truth for
economicbridge.org/privacy and /terms (approved by the directors on
25 September 2026). This writes apps/frontend/src/components/legal/content.ts,
which the two pages render. To change a page: edit the .md, run this, commit
both, deploy the frontend.

A deliberately small converter — headings, paragraphs, lists, tables, bold,
italics and links — because that is all the texts use, and a dependency for
two pages is not worth carrying. Input is our own approved text, never user
input.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parents[1] / "apps" / "frontend" / "src" / "components" / "legal" / "content.ts"


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", re.sub(r"^\d+\.\s*", "", text.lower())).strip("-")


def inline(text: str) -> str:
    s = html.escape(text, quote=False)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<em>\1</em>", s)

    def link(m: re.Match) -> str:
        href = m.group(2)
        if href.startswith(("/", "https://", "mailto:")):
            return f'<a href="{html.escape(href)}">{m.group(1)}</a>'
        return m.group(1)
    s = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", link, s)
    # Plain email addresses become mail links.
    s = re.sub(r"(?<![\w.@/\">])([a-z0-9.]+@economicbridge\.org)",
               r'<a href="mailto:\1">\1</a>', s)
    return s


def render(md: str) -> tuple[str, str, str]:
    """(title, last-updated line, HTML body without the title block)."""
    lines = md.splitlines()
    title = lines[0].removeprefix("# ").strip()
    out: list[str] = []
    para: list[str] = []
    items: list[str] = []
    table: list[list[str]] = []
    updated = ""

    def flush() -> None:
        nonlocal para, items, table
        if para:
            out.append("<p>" + "<br>".join(inline(x) for x in para) + "</p>")
            para = []
        if items:
            out.append("<ul>" + "".join(f"<li>{inline(i)}</li>" for i in items) + "</ul>")
            items = []
        if table:
            head, *rows = table
            out.append(
                '<div class="legal-table"><table><thead><tr>'
                + "".join(f"<th>{inline(c)}</th>" for c in head)
                + "</tr></thead><tbody>"
                + "".join("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in r) + "</tr>" for r in rows)
                + "</tbody></table></div>"
            )
            table = []

    for raw in lines[1:]:
        s = raw.strip()
        if s.startswith("Last updated:"):
            updated = s
            continue
        if s.startswith("|"):
            if para or items:
                flush()
            cells = [c.strip() for c in s.strip("|").split("|")]
            if not all(re.fullmatch(r":?-{2,}:?", c) for c in cells):
                table.append(cells)
        elif s.startswith("- "):
            if para or table:
                flush()
            items.append(s[2:])
        elif not s:
            flush()
        elif s.startswith("### "):
            flush()
            out.append(f'<h3>{inline(s[4:])}</h3>')
        elif s.startswith("## "):
            flush()
            out.append(f'<h2 id="{slug(s[3:])}">{inline(s[3:])}</h2>')
        else:
            if items or table:
                flush()
            para.append(s)
    flush()
    return title, updated, "\n".join(out)


def main() -> None:
    blocks = {}
    for key, src in (("PRIVACY", "PRIVACY_NOTICE.md"), ("TERMS", "TERMS_OF_USE.md")):
        title, updated, body = render((HERE / src).read_text(encoding="utf-8"))
        blocks[key] = (title, updated, body)
    ts = [
        "// GENERATED by docs/legal/build_legal_pages.py from docs/legal/*.md —",
        "// do not edit by hand. Approved by the directors, 25 September 2026.",
        "",
    ]
    for key, (title, updated, body) in blocks.items():
        ts.append(f"export const {key}_TITLE = {json.dumps(title)};")
        ts.append(f"export const {key}_UPDATED = {json.dumps(updated)};")
        ts.append(f"export const {key}_HTML = {json.dumps(body, ensure_ascii=False)};")
        ts.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(ts), encoding="utf-8", newline="\n")
    for key, (title, updated, body) in blocks.items():
        print(f"{key}: {title!r}, {updated!r}, {len(body):,} chars of HTML")


if __name__ == "__main__":
    main()
